// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa6r2R_t9cvOQc7ATIowD3XDJ6mdjaV48',
    appId: '1:1043812735518:web:938901f89ed33a8c906c0f',
    messagingSenderId: '1043812735518',
    projectId: 'misau-2a340',
    authDomain: 'misau-2a340.firebaseapp.com',
    storageBucket: 'misau-2a340.appspot.com',
    measurementId: 'G-2YG5HXY9M7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2gYzioF0Qm-b5mX8UImHxXOfH-0QgbkI',
    appId: '1:1043812735518:android:ea3184b811a817d2906c0f',
    messagingSenderId: '1043812735518',
    projectId: 'misau-2a340',
    storageBucket: 'misau-2a340.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChmP7Bf3wBFM7z9FLy-gfyYPSjJhqoWMA',
    appId: '1:1043812735518:ios:5a854c00e4fd2353906c0f',
    messagingSenderId: '1043812735518',
    projectId: 'misau-2a340',
    storageBucket: 'misau-2a340.appspot.com',
    iosBundleId: 'com.misau.misau',
  );
}
